"""
Google OAuth 2.0 Authentication for FastAPI.

Verifies Google ID tokens sent as Bearer tokens from the Next.js frontend.
"""

from fastapi import HTTPException, Request, status

from app.config import get_settings
from app.core.logger import agent_logger
from app.models.user import User
from app.repositories.user_repo import user_repo


def _extract_bearer_token(request: Request) -> str | None:
    """Extract Bearer token from Authorization header."""
    auth_header = request.headers.get("Authorization", "")
    if auth_header.startswith("Bearer "):
        return auth_header[7:].strip()
    return None


def _verify_jwt_token(token: str) -> dict:
    """
    Verify a standard JWT token generated by NextAuth.
    Returns the decoded payload with email, name, picture, etc.
    """
    settings = get_settings()

    if not settings.AUTH_SECRET:
        raise ValueError("AUTH_SECRET is not configured on the backend.")

    try:
        import jwt

        # Decode the token using the shared AUTH_SECRET
        payload = jwt.decode(
            token,
            settings.AUTH_SECRET,
            algorithms=["HS256"]
        )

        return payload

    except jwt.ExpiredSignatureError:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Session has expired. Please log in again.",
            headers={"WWW-Authenticate": "Bearer"},
        )
    except jwt.InvalidTokenError as e:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=f"Invalid session token: {e}",
            headers={"WWW-Authenticate": "Bearer"},
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=f"Could not validate credentials: {e}",
            headers={"WWW-Authenticate": "Bearer"},
        )


async def get_current_user(request: Request) -> User:
    """
    FastAPI Dependency to authenticate users via NextAuth JWT tokens.

    Expects: Authorization: Bearer <nextauth_jwt_token>

    Uses UserRepository for all database operations instead of
    injecting a raw SQLAlchemy session.
    """
    settings = get_settings()
    token = _extract_bearer_token(request)

    # Dev Mode Bypass
    if not token and settings.is_debug:
        agent_logger.debug("AUTH", "DEBUG mode: using dev user (no token provided)")
        return await user_repo.get_or_create(
            email="dev@localhost",
            name="Dev User",
            picture="",
            role="ADMIN",
        )

    if not token:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authentication required. Send session token as Bearer token.",
            headers={"WWW-Authenticate": "Bearer"},
        )

    # Verify standard JWT Token
    payload = _verify_jwt_token(token)

    email = payload.get("email")
    if not email:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid token payload: missing email.",
        )

    name = payload.get("name", "")
    picture = payload.get("picture", "")

    return await user_repo.get_or_create(
        email=email, name=name, picture=picture,
    )

